package com.didichuxing.model;

import java.io.Serializable;
import java.util.Date;

public class user extends userKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userName
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userSex
     *
     * @mbg.generated
     */
    private Integer usersex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userPwd
     *
     * @mbg.generated
     */
    private String userpwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userEmail
     *
     * @mbg.generated
     */
    private String useremail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userQuestion
     *
     * @mbg.generated
     */
    private String userquestion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userAnswer
     *
     * @mbg.generated
     */
    private String useranswer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userIsOpen
     *
     * @mbg.generated
     */
    private Integer userisopen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userRealName
     *
     * @mbg.generated
     */
    private String userrealname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userBirthDay
     *
     * @mbg.generated
     */
    private String userbirthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userQQ
     *
     * @mbg.generated
     */
    private String userqq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userAddr
     *
     * @mbg.generated
     */
    private String useraddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userRegTime
     *
     * @mbg.generated
     */
    private Date userregtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userLoadDegree
     *
     * @mbg.generated
     */
    private Integer userloaddegree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userLastTime
     *
     * @mbg.generated
     */
    private Date userlasttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userTopic
     *
     * @mbg.generated
     */
    private Integer usertopic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userEliteTopic
     *
     * @mbg.generated
     */
    private Integer userelitetopic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userIntegral
     *
     * @mbg.generated
     */
    private Integer userintegral;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.postalcode
     *
     * @mbg.generated
     */
    private String postalcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.usertel
     *
     * @mbg.generated
     */
    private String usertel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userIdiograph
     *
     * @mbg.generated
     */
    private String useridiograph;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userName
     *
     * @return the value of user.userName
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userName
     *
     * @param username the value for user.userName
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userSex
     *
     * @return the value of user.userSex
     *
     * @mbg.generated
     */
    public Integer getUsersex() {
        return usersex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userSex
     *
     * @param usersex the value for user.userSex
     *
     * @mbg.generated
     */
    public void setUsersex(Integer usersex) {
        this.usersex = usersex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userPwd
     *
     * @return the value of user.userPwd
     *
     * @mbg.generated
     */
    public String getUserpwd() {
        return userpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userPwd
     *
     * @param userpwd the value for user.userPwd
     *
     * @mbg.generated
     */
    public void setUserpwd(String userpwd) {
        this.userpwd = userpwd == null ? null : userpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userEmail
     *
     * @return the value of user.userEmail
     *
     * @mbg.generated
     */
    public String getUseremail() {
        return useremail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userEmail
     *
     * @param useremail the value for user.userEmail
     *
     * @mbg.generated
     */
    public void setUseremail(String useremail) {
        this.useremail = useremail == null ? null : useremail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userQuestion
     *
     * @return the value of user.userQuestion
     *
     * @mbg.generated
     */
    public String getUserquestion() {
        return userquestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userQuestion
     *
     * @param userquestion the value for user.userQuestion
     *
     * @mbg.generated
     */
    public void setUserquestion(String userquestion) {
        this.userquestion = userquestion == null ? null : userquestion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userAnswer
     *
     * @return the value of user.userAnswer
     *
     * @mbg.generated
     */
    public String getUseranswer() {
        return useranswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userAnswer
     *
     * @param useranswer the value for user.userAnswer
     *
     * @mbg.generated
     */
    public void setUseranswer(String useranswer) {
        this.useranswer = useranswer == null ? null : useranswer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userIsOpen
     *
     * @return the value of user.userIsOpen
     *
     * @mbg.generated
     */
    public Integer getUserisopen() {
        return userisopen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userIsOpen
     *
     * @param userisopen the value for user.userIsOpen
     *
     * @mbg.generated
     */
    public void setUserisopen(Integer userisopen) {
        this.userisopen = userisopen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userRealName
     *
     * @return the value of user.userRealName
     *
     * @mbg.generated
     */
    public String getUserrealname() {
        return userrealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userRealName
     *
     * @param userrealname the value for user.userRealName
     *
     * @mbg.generated
     */
    public void setUserrealname(String userrealname) {
        this.userrealname = userrealname == null ? null : userrealname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userBirthDay
     *
     * @return the value of user.userBirthDay
     *
     * @mbg.generated
     */
    public String getUserbirthday() {
        return userbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userBirthDay
     *
     * @param userbirthday the value for user.userBirthDay
     *
     * @mbg.generated
     */
    public void setUserbirthday(String userbirthday) {
        this.userbirthday = userbirthday == null ? null : userbirthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userQQ
     *
     * @return the value of user.userQQ
     *
     * @mbg.generated
     */
    public String getUserqq() {
        return userqq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userQQ
     *
     * @param userqq the value for user.userQQ
     *
     * @mbg.generated
     */
    public void setUserqq(String userqq) {
        this.userqq = userqq == null ? null : userqq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userAddr
     *
     * @return the value of user.userAddr
     *
     * @mbg.generated
     */
    public String getUseraddr() {
        return useraddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userAddr
     *
     * @param useraddr the value for user.userAddr
     *
     * @mbg.generated
     */
    public void setUseraddr(String useraddr) {
        this.useraddr = useraddr == null ? null : useraddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userRegTime
     *
     * @return the value of user.userRegTime
     *
     * @mbg.generated
     */
    public Date getUserregtime() {
        return userregtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userRegTime
     *
     * @param userregtime the value for user.userRegTime
     *
     * @mbg.generated
     */
    public void setUserregtime(Date userregtime) {
        this.userregtime = userregtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userLoadDegree
     *
     * @return the value of user.userLoadDegree
     *
     * @mbg.generated
     */
    public Integer getUserloaddegree() {
        return userloaddegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userLoadDegree
     *
     * @param userloaddegree the value for user.userLoadDegree
     *
     * @mbg.generated
     */
    public void setUserloaddegree(Integer userloaddegree) {
        this.userloaddegree = userloaddegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userLastTime
     *
     * @return the value of user.userLastTime
     *
     * @mbg.generated
     */
    public Date getUserlasttime() {
        return userlasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userLastTime
     *
     * @param userlasttime the value for user.userLastTime
     *
     * @mbg.generated
     */
    public void setUserlasttime(Date userlasttime) {
        this.userlasttime = userlasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userTopic
     *
     * @return the value of user.userTopic
     *
     * @mbg.generated
     */
    public Integer getUsertopic() {
        return usertopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userTopic
     *
     * @param usertopic the value for user.userTopic
     *
     * @mbg.generated
     */
    public void setUsertopic(Integer usertopic) {
        this.usertopic = usertopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userEliteTopic
     *
     * @return the value of user.userEliteTopic
     *
     * @mbg.generated
     */
    public Integer getUserelitetopic() {
        return userelitetopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userEliteTopic
     *
     * @param userelitetopic the value for user.userEliteTopic
     *
     * @mbg.generated
     */
    public void setUserelitetopic(Integer userelitetopic) {
        this.userelitetopic = userelitetopic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userIntegral
     *
     * @return the value of user.userIntegral
     *
     * @mbg.generated
     */
    public Integer getUserintegral() {
        return userintegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userIntegral
     *
     * @param userintegral the value for user.userIntegral
     *
     * @mbg.generated
     */
    public void setUserintegral(Integer userintegral) {
        this.userintegral = userintegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.postalcode
     *
     * @return the value of user.postalcode
     *
     * @mbg.generated
     */
    public String getPostalcode() {
        return postalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.postalcode
     *
     * @param postalcode the value for user.postalcode
     *
     * @mbg.generated
     */
    public void setPostalcode(String postalcode) {
        this.postalcode = postalcode == null ? null : postalcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.usertel
     *
     * @return the value of user.usertel
     *
     * @mbg.generated
     */
    public String getUsertel() {
        return usertel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.usertel
     *
     * @param usertel the value for user.usertel
     *
     * @mbg.generated
     */
    public void setUsertel(String usertel) {
        this.usertel = usertel == null ? null : usertel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userIdiograph
     *
     * @return the value of user.userIdiograph
     *
     * @mbg.generated
     */
    public String getUseridiograph() {
        return useridiograph;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userIdiograph
     *
     * @param useridiograph the value for user.userIdiograph
     *
     * @mbg.generated
     */
    public void setUseridiograph(String useridiograph) {
        this.useridiograph = useridiograph == null ? null : useridiograph.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        user other = (user) that;
        return (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
            && (this.getGroupGroupid() == null ? other.getGroupGroupid() == null : this.getGroupGroupid().equals(other.getGroupGroupid()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getUsersex() == null ? other.getUsersex() == null : this.getUsersex().equals(other.getUsersex()))
            && (this.getUserpwd() == null ? other.getUserpwd() == null : this.getUserpwd().equals(other.getUserpwd()))
            && (this.getUseremail() == null ? other.getUseremail() == null : this.getUseremail().equals(other.getUseremail()))
            && (this.getUserquestion() == null ? other.getUserquestion() == null : this.getUserquestion().equals(other.getUserquestion()))
            && (this.getUseranswer() == null ? other.getUseranswer() == null : this.getUseranswer().equals(other.getUseranswer()))
            && (this.getUserisopen() == null ? other.getUserisopen() == null : this.getUserisopen().equals(other.getUserisopen()))
            && (this.getUserrealname() == null ? other.getUserrealname() == null : this.getUserrealname().equals(other.getUserrealname()))
            && (this.getUserbirthday() == null ? other.getUserbirthday() == null : this.getUserbirthday().equals(other.getUserbirthday()))
            && (this.getUserqq() == null ? other.getUserqq() == null : this.getUserqq().equals(other.getUserqq()))
            && (this.getUseraddr() == null ? other.getUseraddr() == null : this.getUseraddr().equals(other.getUseraddr()))
            && (this.getUserregtime() == null ? other.getUserregtime() == null : this.getUserregtime().equals(other.getUserregtime()))
            && (this.getUserloaddegree() == null ? other.getUserloaddegree() == null : this.getUserloaddegree().equals(other.getUserloaddegree()))
            && (this.getUserlasttime() == null ? other.getUserlasttime() == null : this.getUserlasttime().equals(other.getUserlasttime()))
            && (this.getUsertopic() == null ? other.getUsertopic() == null : this.getUsertopic().equals(other.getUsertopic()))
            && (this.getUserelitetopic() == null ? other.getUserelitetopic() == null : this.getUserelitetopic().equals(other.getUserelitetopic()))
            && (this.getUserintegral() == null ? other.getUserintegral() == null : this.getUserintegral().equals(other.getUserintegral()))
            && (this.getPostalcode() == null ? other.getPostalcode() == null : this.getPostalcode().equals(other.getPostalcode()))
            && (this.getUsertel() == null ? other.getUsertel() == null : this.getUsertel().equals(other.getUsertel()))
            && (this.getUseridiograph() == null ? other.getUseridiograph() == null : this.getUseridiograph().equals(other.getUseridiograph()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        result = prime * result + ((getGroupGroupid() == null) ? 0 : getGroupGroupid().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getUsersex() == null) ? 0 : getUsersex().hashCode());
        result = prime * result + ((getUserpwd() == null) ? 0 : getUserpwd().hashCode());
        result = prime * result + ((getUseremail() == null) ? 0 : getUseremail().hashCode());
        result = prime * result + ((getUserquestion() == null) ? 0 : getUserquestion().hashCode());
        result = prime * result + ((getUseranswer() == null) ? 0 : getUseranswer().hashCode());
        result = prime * result + ((getUserisopen() == null) ? 0 : getUserisopen().hashCode());
        result = prime * result + ((getUserrealname() == null) ? 0 : getUserrealname().hashCode());
        result = prime * result + ((getUserbirthday() == null) ? 0 : getUserbirthday().hashCode());
        result = prime * result + ((getUserqq() == null) ? 0 : getUserqq().hashCode());
        result = prime * result + ((getUseraddr() == null) ? 0 : getUseraddr().hashCode());
        result = prime * result + ((getUserregtime() == null) ? 0 : getUserregtime().hashCode());
        result = prime * result + ((getUserloaddegree() == null) ? 0 : getUserloaddegree().hashCode());
        result = prime * result + ((getUserlasttime() == null) ? 0 : getUserlasttime().hashCode());
        result = prime * result + ((getUsertopic() == null) ? 0 : getUsertopic().hashCode());
        result = prime * result + ((getUserelitetopic() == null) ? 0 : getUserelitetopic().hashCode());
        result = prime * result + ((getUserintegral() == null) ? 0 : getUserintegral().hashCode());
        result = prime * result + ((getPostalcode() == null) ? 0 : getPostalcode().hashCode());
        result = prime * result + ((getUsertel() == null) ? 0 : getUsertel().hashCode());
        result = prime * result + ((getUseridiograph() == null) ? 0 : getUseridiograph().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", username=").append(username);
        sb.append(", usersex=").append(usersex);
        sb.append(", userpwd=").append(userpwd);
        sb.append(", useremail=").append(useremail);
        sb.append(", userquestion=").append(userquestion);
        sb.append(", useranswer=").append(useranswer);
        sb.append(", userisopen=").append(userisopen);
        sb.append(", userrealname=").append(userrealname);
        sb.append(", userbirthday=").append(userbirthday);
        sb.append(", userqq=").append(userqq);
        sb.append(", useraddr=").append(useraddr);
        sb.append(", userregtime=").append(userregtime);
        sb.append(", userloaddegree=").append(userloaddegree);
        sb.append(", userlasttime=").append(userlasttime);
        sb.append(", usertopic=").append(usertopic);
        sb.append(", userelitetopic=").append(userelitetopic);
        sb.append(", userintegral=").append(userintegral);
        sb.append(", postalcode=").append(postalcode);
        sb.append(", usertel=").append(usertel);
        sb.append(", useridiograph=").append(useridiograph);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}